#!/usr/bin/env python
# coding: utf-8

# In[5]:


get_ipython().system('conda install pydicom --channel conda-forge -y')


# In[21]:


get_ipython().system('conda install -c conda-forge gdcm')


# In[18]:


import matplotlib.pyplot as plt
import pydicom
import pydicom.data

# Full path of the DICOM file is passed in base
base = "./"
pass_dicom = "img4.dcm" # file name is 1-12.dcm

# enter DICOM image name for pattern
# result is a list of 1 element
filename = pydicom.data.data_manager.get_files(base, pass_dicom)[0]

ds = pydicom.dcmread(filename)

plt.imshow(ds.pixel_array, cmap=plt.cm.bone) # set the color map to bone
plt.show()


# In[15]:


get_ipython().system('ls')


# In[20]:


get_ipython().system('conda install numpy')


# In[ ]:




